### ISSUE TITLE
PhaseDiagram.binary_vle() Unable to Calculation Binary Mixtures without Critical Point

### ISSUE THREAD

**Issue by ErichMace** [feos-org/feos#125]
When creating a binary phase diagram using PhaseDiagram.binary_vle() the current algorithm is not able to handle systems where a critical point does not exist. This would be the case, for example, for the mixture Ar-NH3 at 298.15 K.

![image](https://user-images.githubusercontent.com/119608456/215077543-3e034085-99f5-41f7-900d-dc0e213381e1.png)
[T=298K.zip](https://github.com/feos-org/feos/files/10518443/T.298K.zip)

**Comment by g-bauer** [comment]
The binary VLE routine currently first tries to compute the pure-substance VLEs and - if a component is super-critical - will try to compute the critical point of the mixture which here fails. 

Now, with the next version it will be possible to create a `PhaseDiagram` object from single VLE's. So you will be able to calculate VLE's using one of the available methods (tp-flash, dew- and bubble points). See #113 

In the future, we may introduce a way to handle this issue within the `binary_vle` routine.

**Comment by prehner** [comment]
I think for these kind of "difficult" phase equilibria involving highly volatile components like argon, hydrogen, or helium, the solution presented in #113 is sufficient for now and therefore I'm closing this issue.
