### ISSUE TITLE
Access to I&EC Paper

### ISSUE THREAD

**Issue by WarthogARJ** [feos-org/feos#140]
Hi,
I was reading of your work, and wanted to read your in-print paper "FeOs: An Open-Source Framework for Equations of State and Classical Density Functional Theory".
But it's behind a paywall I hve no access to.

Could you perhaps post an author-copy?
But maybe I'm jumping the gun?

No offence, but it seems a contradiction in terms to have a paper on Open Source that is not itself Open source....:}
I tried SciHub and LibraryGenesis but no luck.

**Comment by g-bauer** [comment]
Hi. Thank you for the interest in FeOs. We can understand the frustration regarding the access limitation. 

However, we would like to emphasise that to use and understand the code, the documentation and examples of are absolutely sufficient and we have put a lot of time and effort into them.

If you have any further questions regarding the publication, please do not hesitate to contact us by email.

**Comment by g-bauer** [comment]
@ianhbell Thanks for the comment. That's a good idea. We will discuss this option.

**Comment by prehner** [comment]
FYI, the publication is now published as open access.
