### ISSUE TITLE
More general association schemes

### ISSUE THREAD

**Issue by prehner** [feos-org/feos#143]
Some recent and some not so recent publications show the advantage of incorporating association contributions for binary mixtures in which both pure components are not self-associating. Conceptually this is straightforward to implement in any SAFT model. The question is, how the additional parameters can be specified, especially because they have no effect on pure component properties.

**Comment by g-bauer** [comment]
As discussed, we could add those parameters into the existing binary records. We'd need to discuss how this would work in detail and how we handle cases where both components have association parameters and there is a binary entry as well (which could technically happen).

If we add it as binary record, we have to adjust the `AssociationParameters` struct and how it's constructed.
