### ISSUE TITLE
Association schemes

### ISSUE THREAD

**Issue by marcosfelt** [feos-org/feos#147]
Is it possible to pass in multiple `AssociationRecord`s to PC-SAFT so that I could have multiple association sites on a molecule?

**Comment by prehner** [comment]
Hello, that is fascinating timing. I am just finishing an update that allows for more flexible association schemes.

There are a lot of possible ways that association can be included in SAFT models, however, to keep it fast and ergonomic (especially for mixtures), we usually only consider specific subsets of possible association schemes.

If you let me know what your use case would be, i can see whether it fits in the planned update.

**Comment by marcosfelt** [comment]
Thanks for the quick response. To be honest, I am still not sure which association schemes yet since I will need to do some testing (if I even get to it!), so I'd suggest not changing your plans for me :) I'll use whatever you set up!
