### ISSUE TITLE
Example on how to optimize parameters (m, sigma, epsilon_k) of PC-SAFT 

### ISSUE THREAD

**Issue by RayleighSun** [feos-org/feos#168]
Dear Dr. Rehner and Dr. Bauer, is there a program to optimize the three parameters (m, sigma, epsilon_k) related to PC-SAFT, say propane, with the experimental data of vapor pressure and saturated liquid density as input? @g-bauer @prehner

**Comment by g-bauer** [comment]
Hi!

Better documentation for parameter adjustment is a topic we are currently working on. Until a properly documented notebook is added to this repository, I created a (undocumented) example [here](https://github.com/feos-org/demo-notebooks/blob/main/parameter_adjustment/adjust_non_polar_non_asssociating.ipynb).

It uses data from the NIST WebBook (for hexane) and includes some Gaussian distortion to simulate statistical uncertainties and highlight robust regression. It also utilizes the `Estimator` and `DataSet` structures that FeOs provides to make working with experimental data easier. Hope it helps.

**Comment by RayleighSun** [comment]
That's perfect! Thanks!
