### ISSUE TITLE
Polarizable models?

### ISSUE THREAD

**Issue by ianhbell** [feos-org/feos#198]
Have you thought to possibly integrate the polarizable model of Kleiner and Gross in FEoS? I am struggling mightily to get this general approach to work and would love if I could try to understand what by looking at a parallel implementation in rust.

**Comment by prehner** [comment]
As far as I know, there are no plans to implement that.

**Comment by ianhbell** [comment]
Too bad, the polarizable models are an interesting approach for handling polar fluids.
