### ISSUE TITLE
Output the fraction of non-bonded association sites

### ISSUE THREAD

**Issue by DiegoTMelfi** [feos-org/feos#210]
Hi,

Is it possible to output the fraction of non-bounded association sites (Xa) from feos?

Thank you!

**Comment by prehner** [comment]
Hello,
thank you for the question. It would be a nice feature to have in various circumstances, but the generic implementation of equations of states and properties in feos is currently not well suited for that. It would require a significant rewrite of the core components of the code and is thus not something that we have planned for the near future.

**Comment by DiegoTMelfi** [comment]
Hi Prehner,
Thank you for the quick response!
