### ISSUE TITLE
`PcSaftParameters.from_records` can not be used without binary parameters

### ISSUE THREAD

**Issue by prehner** [feos-org/feos#28]
```python
c1 = PureRecord(Identifier(), 1.0, PcSaftRecord(1, 3.0, 150.0))
c2 = PureRecord(Identifier(), 1.0, PcSaftRecord(1, 3.0, 150.0))
func = HelmholtzEnergyFunctional.pcsaft(PcSaftParameters.from_records([c1, c2]))
```
can not be run due to a missing argument. Passing an empty list results in an `unwrap` error.

**Comment by g-bauer** [comment]
Replace `unwrap` with `panic` with informative error message [here](https://github.com/feos-org/feos/blob/b3180fb38b7ac0ef1d52b87572a7c6daf36afff9/feos-core/src/parameter/mod.rs#L95-L96)
