### ISSUE TITLE
Using the estimator tool

### ISSUE THREAD

**Issue by marcosfelt** [feos-org/feos#78]
Is there a tutorial on how to use the estimator tool from python? I couldn't seem to find one, but I might be missing something.

**Comment by marcosfelt** [comment]
I would want to adjust equation of state parameters. A tutorial would be great! Thanks 😁

**Comment by g-bauer** [comment]
I opened a tracking issue (#82) for documentation/notebook(s) for this issue. We are currently working on parallelization of these features so this may take some time.
