### ISSUE TITLE
Missing Contributions objects from the feos.pcsaft module

### ISSUE THREAD

**Issue by defencedog** [feos-org/feos#80]
Cannot run this notebook because of above error `pcsaft_phase_diagram.ipynb`

**Comment by g-bauer** [comment]
Hey, thanks for trying out FeOs. You are right, the text above the input statements is out of date. The `Contributions` object can be imported from the `feos.eos` module, i.e. `from feos.eos import Contributions` should do the trick. I will update the documentation.

In the notebook, however, we use `from feos.eos import *`. You should be able to run the whole notebook as is. Are you using [this notebook](https://github.com/feos-org/feos/blob/main/examples/pcsaft_phase_diagram.ipynb).

**Comment by defencedog** [comment]
@g-bauer extremely thanks. Will you be updating notebooks in git as per latest API ...it means a lot for new users

**Comment by g-bauer** [comment]
I will fix the text. Does the notebook work properly? On my machine with the latest version of FeOs it does. Also, you can always check the [Python API here](https://feos-org.github.io/feos/api/index.html).  And [this is the link](https://feos-org.github.io/feos/api/eos.html) to the `feos.eos` module where the `Contributions` object is exported.

**Comment by defencedog** [comment]
@g-bauer Yes it works properly. Extremely thanks
